/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'OnellMiranda' at '02-08-16 10:58' with Gradle 2.14
 *
 * @author OnellMiranda, @date 02-08-16 10:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
